package classes;

/**
 *
 * @author Meu Computador
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        LblFala.setText("<html>Estou pensando em um número entre <strong>1 e 5</strong>. Tente adivinhar.<html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblFala = new javax.swing.JLabel();
        VlChute = new javax.swing.JSpinner();
        BtnChute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblFala.setBackground(new java.awt.Color(255, 255, 255));
        LblFala.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblFala.setForeground(new java.awt.Color(0, 0, 0));
        LblFala.setText("Duvido se acerta o número que eu to pensando mano ");
        getContentPane().add(LblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 610, 70));

        VlChute.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        VlChute.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(VlChute, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 80, 100));

        BtnChute.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnChute.setText("Chuta ai ksksks");
        BtnChute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChuteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChute, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 220, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Valor do Chute");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChuteActionPerformed
        double n = 1 +  Math.random() * (6 - 1);
        int valor = (int) n;
        
        int chute = Integer.parseInt(VlChute.getValue().toString());
        
        String f1 = "<html>Puts você errou ksksk mt ruim. Eu tinha pensado no <html>" + valor;
        String f2 = "<html>Boa mano, voce <strong>acertou</strong>. Eu pensei em<html> " + valor;
        
        String res = chute == valor ? f2 : f1;
        LblFala.setText(res);
    }//GEN-LAST:event_BtnChuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChute;
    private javax.swing.JLabel LblFala;
    private javax.swing.JSpinner VlChute;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
